jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: microsoft
        java-version: '17'
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build
    - continue-on-error: true
      name: Copy together artifacts
      run: 'mkdir dist

        cp Common/build/libs/*.jar dist

        cp CommonApi/build/libs/*.jar dist

        cp Core/build/libs/*.jar dist

        cp Fabric/build/libs/*.jar dist

        cp FabricApi/build/libs/*.jar dist

        cp Forge/build/libs/*.jar dist

        cp ForgeApi/build/libs/*.jar dist

        cp NeoForge/build/libs/*.jar dist

        cp NeoForgeApi/build/libs/*.jar dist

        cp Gui/build/libs/*.jar dist

        cp Library/build/libs/*.jar dist

        '
      shell: bash
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        path: dist/*
name: Build and Test
on:
  repository_dispatch:
    types: trigger-ga___build.yml
